# Generated by Django 4.2.4 on 2023-09-09 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_historicalknowledge_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalknowledge",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="knowledge",
            name="metadata",
        ),
    ]
