# Generated by Django 4.2.4 on 2023-09-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_model_historicalmodel_chat_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="is_template",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalchat",
            name="is_template",
            field=models.BooleanField(default=False),
        ),
    ]
