# Generated by Django 4.2.4 on 2023-09-23 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_rename_knowledgecategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalknowledge',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmessage',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, default=None, dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, default=None, dimensions=1536, null=True),
        ),
    ]
