version: '3'
services:
  app:
    build: .
    command: [./scripts/start.sh]

    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgres-data:/var/lib/postgresql/data
