# Generated by Django 4.2.4 on 2023-08-26 16:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_userprofile_historicaluserprofile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Conversation",
            new_name="Chat",
        ),
        migrations.RenameModel(
            old_name="HistoricalConversation",
            new_name="HistoricalChat",
        ),
        migrations.AlterModelOptions(
            name="historicalchat",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical chat",
                "verbose_name_plural": "historical chats",
            },
        ),
        migrations.RenameField(
            model_name="historicalmessage",
            old_name="discussion",
            new_name="chat",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="discussion",
            new_name="chat",
        ),
    ]
