# Generated by Django 4.2.4 on 2023-08-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_conversation_chat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="response",
            name="message",
        ),
        migrations.RemoveField(
            model_name="response",
            name="user",
        ),
        migrations.AddField(
            model_name="historicalmessage",
            name="type",
            field=models.CharField(
                choices=[
                    ("LLM_RESPONSE", "LLM Response"),
                    ("USER_MESSAGE", "User Message"),
                    ("MODERATOR_MESSAGE", "Moderator Message"),
                ],
                default="USER_MESSAGE",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="type",
            field=models.CharField(
                choices=[
                    ("LLM_RESPONSE", "LLM Response"),
                    ("USER_MESSAGE", "User Message"),
                    ("MODERATOR_MESSAGE", "Moderator Message"),
                ],
                default="USER_MESSAGE",
                max_length=255,
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalResponse",
        ),
        migrations.DeleteModel(
            name="Response",
        ),
    ]
