# Generated by Django 4.2.4 on 2023-08-27 15:11

from django.db import migrations, models
import pgvector.django

from pgvector.django import VectorExtension

class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_knowledge_knowledgequestionembedding_and_more"),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name="historicalknowledgequestionembedding",
            name="embedding_model",
            field=models.CharField(
                choices=[("text-embedding-ada-002", "ADA2")], default="text-embedding-ada-002", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="knowledgequestionembedding",
            name="embedding_model",
            field=models.CharField(
                choices=[("text-embedding-ada-002", "ADA2")], default="text-embedding-ada-002", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="historicalknowledgequestionembedding",
            name="embedding",
            field=pgvector.django.VectorField(dimensions=1536),
        ),
        migrations.AlterField(
            model_name="knowledgequestionembedding",
            name="embedding",
            field=pgvector.django.VectorField(dimensions=1536),
        ),
    ]
